myproject03/myproject03/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage),
    path("about/", views.about),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject03/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.posts_list, name="list"),
    path("new-post", views.post_new, name="new-post"),
    path("<slug:slug>", views.post_page, name="page")
]

myproject03/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

myproject03/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default="fallback.png", blank=True)

    def __str__(self):
        return self.title
    

myproject03/users/models.py
from django.db import models

# Create your models here.

myproject03/myproject03/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

myproject03/posts/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.
def posts_list(request):
    posts = Post.objects.all()
    return render(request, "posts/posts_list.html", {"posts":posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, "posts/post_page.html", {"post":post})


@login_required(login_url="/users/login/")
def post_new(request):
    return render(request, "posts/post_new.html")

myproject03/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form":form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form":form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

myproject03/posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
    New Post
{% endblock  %}

{% block content %}
    <section>
        <h1>New Post</h1>
    </section>
{% endblock  %}

myproject03/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title }}
{% endblock  %}

{% block content %}
    <section>
        <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}">
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock  %}

myproject03/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Posts
{% endblock  %}

{% block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts %}
            <article class="post">
                <h2>
                    <a href="{% url "posts:page" %}">{{ post.title }}</a>
                </h2>
                <p>{{ post.date }}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock  %}

myproject03/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock  %}

myproject03/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock  %}

myproject03/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Django App
    </title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="{% static "js/main.js" %}"defer></script>
</head>
<body>
    <nav>
        <a href="/">🏠</a> |
        <a href="/about">😀</a> |
        <a href="{% url "posts:list" %}">📰</a> |
        {% if user.is_authenticated %}
            <a href="{% url "posts:new-post" %}">🆕</a>
            <form class="logout" action="{% url "users:logout" %}"method="post">
                {% csrf_token %}
                <button class="logout-button">👋</button>
            </form>
        {% else %}
            <a href="{% url "users:register" %}">🚀</a> |
            <a href="{% url "users:login" %}">🔒</a>
        {% endif %}
    </nav>
    <main>
        {% block content %}{% endblock  %}
    </main>
</body>
</html>

myproject03/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    User Login
{% endblock  %}

{% block content %}
    <h1>User Login</h1>
    <form class="form-with-validation" action="{% url "users:login" %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock  %}

myproject03/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    Register A New User
{% endblock  %}

{% block content %}
    <h1>Register A New User</h1>
    <form class="form-with-validation" action="{% url "users:register" %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock  %}